// Copyright (c) 2022 Anders Xiao. All rights reserved.
// https://github.com/endink

#pragma once
#include "Stats/Stats2.h"


DECLARE_STATS_GROUP(TEXT("MediaPipe4U Stats"),STATGROUP_MediaPipe, STATCAT_MediaPipe4U);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Pose Solve"), STAT_PoseSolve, STATGROUP_MediaPipe, MEDIAPIPE_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Hand Solve"), STAT_HandSolve, STATGROUP_MediaPipe, MEDIAPIPE_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Head Solve"), STAT_HeadSolve, STATGROUP_MediaPipe, MEDIAPIPE_API)
DECLARE_CYCLE_STAT_EXTERN(TEXT("Location Solve"), STAT_LocationSolve, STATGROUP_MediaPipe, MEDIAPIPE_API)

DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN(TEXT("Image Source FPS"), STAT_ImageSourceFPS, STATGROUP_MediaPipe, MEDIAPIPE_API);
DECLARE_FLOAT_ACCUMULATOR_STAT_EXTERN(TEXT("Image Streaming FPS"), STAT_ImageStreamingFPS, STATGROUP_MediaPipe, MEDIAPIPE_API);

DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Image Frame Width"), STAT_FrameWidth, STATGROUP_MediaPipe, MEDIAPIPE_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Image Frame Height"), STAT_FrameHeight, STATGROUP_MediaPipe, MEDIAPIPE_API);

DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Frame Pool Idle"), STAT_FramePoolIdle, STATGROUP_MediaPipe, MEDIAPIPE_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Frame Pool Busy"), STAT_FramePoolBusy, STATGROUP_MediaPipe, MEDIAPIPE_API);

DECLARE_CYCLE_STAT_EXTERN(TEXT("Face Live Link Publish"), STAT_FaceLiveLinkPub, STATGROUP_MediaPipe, MEDIAPIPE_API)